### ISSUE TITLE
Not recognized

### ISSUE THREAD

**Issue by Apocatastasis** [embuc/k480_conf#4]
DRIVER=hid-generic
HID_ID=0005:0000046D:0000B33D
HID_NAME=Keyboard K480
HID_PHYS=00:03:7a:73:1f:dc
HID_UNIQ=34:88:5d:7e:d0:68
MODALIAS=hid:b0005g0001v0000046Dp0000B33D
Gives: The given device is not a supported Logitech keyboard: Operation not permitted
Product : ffffb33d

**Comment by peroty** [comment]
I am getting the same error on Ubuntu 18.04.

Identifying Keyboard:
sudo cat /sys/class/hidraw/hidraw4/device/uevent
DRIVER=hid-generic
HID_ID=0005:0000046D:0000B33D
HID_NAME=Keyboard K480
HID_PHYS=00:02:72:1f:58:3c
HID_UNIQ=34:88:5d:9b:d8:de
MODALIAS=hid:b0005g0001v0000046Dp0000B33D

When I try to run it:
sudo ./k480_conf -d /dev/hidraw4 -f on
The given device is not a supported Logitech keyboard: Operation not permitted
Product : ffffb33d

**Comment by parkerlreed** [comment]
Same here on Arch

```
alarm@alarm k480_conf]$ cat /sys/class/hidraw/hidraw0/device/uevent 
DRIVER=hid-generic
HID_ID=0005:0000046D:0000B33D
HID_NAME=Keyboard K480
HID_PHYS=a4:38:cc:f7:ff:bc
HID_UNIQ=34:88:5d:c5:e9:83
MODALIAS=hid:b0005g0001v0000046Dp0000B33D
[alarm@alarm k480_conf]$ sudo ./k480_conf -d /dev/hidraw0 -f on
The given device is not a supported Logitech keyboard: Operation not permitted
Product : ffffb33d
[alarm@alarm k480_conf]$ 
```

**Comment by cryoff** [comment]
Same here on ubuntu 18.04 + lenovo T480

**Comment by joboyx** [comment]
Same with me :|

```
Linux ht-lt003 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$>cat /sys/class/hidraw/hidraw0/device/uevent                                                                                               DRIVER=hid-generic
HID_ID=0005:0000046D:0000B33D
HID_NAME=Keyboard K480
HID_PHYS=98:54:1b:20:72:cb
HID_UNIQ=34:88:5d:79:66:03
MODALIAS=hid:b0005g0001v0000046Dp0000B33D

$> sudo ./k480_conf -d /dev/hidraw0 -f on                                                                                                    The given device is not a supported Logitech keyboard: Operation not permitted
Product : ffffb33d
```

**Comment by mendes-davi** [comment]
Hey @joboyx @cryoff @parkerlreed @peroty @Apocatastasis 

I found the solution for this issue. I guess the newer versions of the K480 with `Product : ffffb33d` use the same key sequence of the Logitech K380. The fix has been merged to repo!

**Comment by joboyx** [comment]
@mendes-davi, yeah quickly inspecting the code I found out that if I add `b33d` code to the if clause I should be able to make it work. However after doing that. FN keys are still not toggled for Logitech k480 keyboard.

----

After looking at your changes, my guess was right, there's a different sequence or flags to enable for b33d. Which I didn't update in my code coz I don't know where to look for it. So I'll try again using your updated code. And let you know. Thank you very much!

**Comment by joboyx** [comment]
@mendes-davi, BIG THANKS! :+1: It is now working.

I think we can close this ticket now.
